# Generated by Django 6.0.4 on 2026-04-18 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
